<?php
/* Author: Yoni <yoni@unlockforus.com> - Courtesy <www.unlockforus.com> */
$labels = array();
$labels['pluginname'] = 'Notificador Webmail';
$labels['plugindescription'] = 'Un complemento del navegador para la notificación de nuevos mensajes.';
$labels['webmailnotifieraddon'] = 'Descarga el complemento de notificación de correo nuevo para %s';
$labels['webmailnotifierscript'] = 'Descarga el script de notificación de correo nuevo para %s';
$labels['webmailnotifierflag'] = 'Notificar si hay mensajes';
$labels['webmailnotifierfolders'] = 'Comprobar carpetas';
$labels['recent'] = 'Nuevos';
$labels['unseen'] = 'No leídos';
?>